name: Deploy Dev

on:
  push:
    branches: [test]

env:
  ACCOUNT_ID: CVETDEV
  ACCOUNT_USERNAME: cvetdev_admin
  ACCOUNT_PASSWORD: cvetdev_admin
  CLIENT_ID: CVETDEV
  CLIENT_SECRET: 9c3acda0-5623-4836-b738-5dc8264d8e32
  BRANCH: test
  PLUGIN_VERSION: "1.0.1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: test

      - name: Run build plugin jar
        working-directory: covetrus project/cvet
        if: github.ref == 'refs/heads/test'  # Only deploy on pushes to main branch
        run: |
         - mvn -B clean package -DskipTests
         - mkdir -p $GITHUB_WORKSPACE/artifacts
         - cp target/*.jar $GITHUB_WORKSPACE/artifacts
         - ls -lah $GITHUB_WORKSPACE/artifacts
