# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:       
    - name : setting
      run: mvn -s settings.xml clean install
      
    - name: Build with Maven
      if: github.ref == 'refs/heads/main'  # Only deploy on pushes to main branch
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: |
       chmod +x  ./deployment/retailer1/rubix-install.sh
       ./deployment/retailer1/rubix-install.sh
      env:
        API_HOST: ${{ secrets.DEV_API_HOST }}
        DEV_ACCOUNT: ${{ vars.DEV_ACCOUNT }}
        GITHUB_TOKEN: ${{ github.token }}
