name: Deploy Dev

on:
  push:
    branches: [test]

env:
  ACCOUNT_ID: CVETDEV
  ACCOUNT_USERNAME: cvetdev_admin
  ACCOUNT_PASSWORD: cvetdev_admin
  CLIENT_ID: CVETDEV
  CLIENT_SECRET: 9c3acda0-5623-4836-b738-5dc8264d8e32
  BRANCH: test
  PLUGIN_VERSION: "1.0.2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: test

      - name: Run build plugin jar
        working-directory: covetrus project/cvet
        run: |
          mvn versions:set -DnewVersion=${{env.PLUGIN_VERSION}} -f pom.xml --no-transfer-progress
          mvn clean package -Drubix.osgi.symbolic.name=${{env.ACCOUNT_ID}}.nitish -DskipTests --no-transfer-progress

      - name: Deploy
        working-directory: "covetrus project/cvet"
        shell: /bin/bash -xe {0}
        run: |
          echo -e "\nDEPLOYING\n"
          VERSION="${{env.PLUGIN_VERSION}}"
          cp $(find ./target -type f -name 'rubix-plugin-cvet*.jar') ./rubix-plugin-cvet-${VERSION}.jar
          echo "VERSION: ${VERSION}"
          BEARER=$(curl -sX POST "https://cvetdev.sandbox.api.fluentretail.com/oauth/token?username=$ACCOUNT_USERNAME&password=$ACCOUNT_PASSWORD&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&grant_type=password" | jq -r '.access_token')
          OUTPUT=$(curl -sX POST \
              -F "file=@./rubix-plugin-cvet-${VERSION}.jar" \
              -H "Authorization: Bearer ${BEARER}" \
              -H "fluent.account: CVETDEV" \
              -H "Content-Type: multipart/form-data" \
              "https://cvetdev.sandbox.api.fluentretail.com:443/orchestration/rest/v1/plugin/upload")

          STATUS=$(echo ${OUTPUT} | jq -r '.status')
          if [[ ${STATUS} == 200 ]]; then
              echo "Deploy successful"
              echo ${OUTPUT}
          else
              echo "Deploy failed"
              echo ${OUTPUT}
              exit 1
          fi

      - name: Install
        working-directory: covetrus project/cvet
        run: |
          echo -e "\nINSTALLING\n"
          VERSION="${{env.PLUGIN_VERSION}}"
          BEARER=$(curl -sX POST "https://cvetdev.sandbox.api.fluentretail.com/oauth/token?username=$ACCOUNT_USERNAME&password=$ACCOUNT_PASSWORD&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&grant_type=password" | jq -r '.access_token')
          curl -sX POST \
              -H "Authorization: Bearer ${BEARER}" \
              -H "fluent.account: CVETDEV" \
              -H "Content-Type: application/json" \
              --data "{\"accountId\":\"CVETDEV\",\"bundleName\":\"CVETDEV.nitish::${VERSION}\"}" \
              "https://CVETDEV.sandbox.api.fluentretail.com:443/orchestration/rest/v1/plugin/install"

      - name: Status
        working-directory: covetrus project/cvet
        run: |
          echo -e "\nSTATUS\n"
          VERSION="${{env.PLUGIN_VERSION}}"
          BEARER=$(curl -sX POST "https://cvetdev.sandbox.api.fluentretail.com/oauth/token?username=$ACCOUNT_USERNAME&password=$ACCOUNT_PASSWORD&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&grant_type=password" | jq -r '.access_token')
          OUTPUT=$(curl -sX GET \
              -H "Authorization: Bearer ${BEARER}" \
              -H "fluent.account: CVETDEV" \
              -H "Content-Type: application/json" \
              "https://CVETDEV.sandbox.api.fluentretail.com:443/orchestration/rest/v1/plugin/CVETDEV.nitish::${VERSION}/status")
          STATUS=$(echo ${OUTPUT} | jq -r '.bundleStatus')
          if [[ ${STATUS} == "ACTIVE" ]]; then
              echo "Deploy successful"
              echo ${OUTPUT}
          else
              echo "Deploy failed"
              echo ${OUTPUT}
              exit 1
          fi
