name: Maven Package

on:
  push:
    branches: [test,main]

env:
  ACCOUNT_ID: CVETDEV
  ACCOUNT_USERNAME: cvetdev_admin
  ACCOUNT_PASSWORD: cvetdev_admin
  CLIENT_ID: CVETDEV
  CLIENT_SECRET: 9c3acda0-5623-4836-b738-5dc8264d8e32
  BRANCH: test
  PLUGIN_VERSION: "1.0.2"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: test

      - name: Run build plugin jar
        working-directory: covetrus-project/cvet
        run: |
          mvn -B clean install -DskipTests
          mkdir -p ${GITHUB_WORKSPACE}/artifacts
          cp target/*.jar ${GITHUB_WORKSPACE}/artifacts
          ls -lah ${GITHUB_WORKSPACE}/artifacts

      - name: Run the deploy
        if: ${{ github.ref == 'refs/heads/test' }}
        run: |
          chmod +x ./covetrus-project/cvet/deployment/retailer1/rubix-install.sh
          ./covetrus-project/cvet/deployment/retailer1/rubix-install.sh
          
        env:
          API_HOST: ${{ vars.DEV_API_HOST }}
          DEV_ACCOUNT: ${{ vars.DEV_ACCOUNT }}
          RETAILER_PASSWORD: ${{ secrets.DEV_RETAILER_PASSWORD }}
          PLUGIN_NAME: ${{ vars.DEV_PLUGIN_NAMESPACE }}
          RETAILER_USERNAME: ${{ vars.DEV_RETAILER_USERNAME }}
          CLIENT_SECRET: ${{ secrets.DEV_CLIENT_SECRET }}
          GIT_EMAIL: ${{ vars.GLOBAL_GIT_EMAIL_ID }}
          GIT_USERNAME: ${{ vars.GLOBAL_GIT_USER_NAME }}
          GIT_ACCESS_TOKEN: ${{ secrets.DEV_GLOBAL_GIT_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
