# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
     

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: |
       chmod +x  ./deployment/retailer1/rubix-install.sh
       ./deployment/retailer1/rubix-install.sh
      env:
        API_HOST: ${{ secrets.DEV_API_HOST }}
        DEV_ACCOUNT: ${{ vars.DEV_ACCOUNT }}
